WIP: random32: make siprand_state 4 longs instead of an array
I've met this strange error while making for allmodconfig:

  scripts/kconfig/conf  --syncconfig Kconfig
    CALL    scripts/checksyscalls.sh
    CALL    scripts/atomic/check-atomics.sh
    DESCEND  objtool
    CC      lib/random32.o
  In file included from ./include/asm-generic/percpu.h:7,
                   from ./arch/x86/include/asm/percpu.h:390,
                   from ./arch/x86/include/asm/preempt.h:6,
                   from ./include/linux/preempt.h:78,
                   from ./include/linux/percpu.h:6,
                   from lib/random32.c:36:
  lib/random32.c:323:30: error: structure variable 'net_rand_state' with 'latent_entropy' attribute has a non-integer field 'v'
    323 | static DEFINE_PER_CPU(struct siprand_state, net_rand_state) __latent_entropy;
        |                              ^~~~~~~~~~~~~
  ./include/linux/percpu-defs.h:95:38: note: in definition of macro 'DEFINE_PER_CPU_SECTION'
     95 |  __PCPU_ATTRS(sec) __weak __typeof__(type) name
        |                                      ^~~~
  lib/random32.c:323:8: note: in expansion of macro 'DEFINE_PER_CPU'
    323 | static DEFINE_PER_CPU(struct siprand_state, net_rand_state) __latent_entropy;
        |        ^~~~~~~~~~~~~~
  make[2]: *** [lib/random32.o] Error 1
  make[1]: *** [lib] Error 2
  make: *** [__sub-make] Error 2

It goes away when the members of the struct are all individual
integers instead of an array of integers. We really don't care
since they're always used separately, let's change this.